apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
type: Opaque
stringData:
  accessToken: "onetwo"
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-k8s-stack5
spec:
  workspaceTemplate:
    spec:
      image: k3d-myreg:49474/pulumifull:latest
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  stack: stk1
  projectRepo: https://github.com/fsedano/argotest
  repoDir: /app/pulumiapp
  branch: "refs/heads/master"
  destroyOnFinalize: true